name: Test-Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: 'Login to docker with GHCR'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build with Maven
        working-directory: ./
        run: | 
          mvn -B --update-snapshots package -P dockerize
          docker build ./docker -f ./docker/Dockerfile -t ghcr.io/${{ github.repository_owner }}/stevedore:v0.0.1
          docker push ghcr.io/${{ github.repository_owner }}/stevedore:v0.0.1
          
      - name: Send dispatch to Repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: com619-2021/IntegrationA 
          event-type: deploy
          client-payload: '{"image_owner": "STEVEDORE_IMAGE" ,"image_tag": "ghcr.io/${{ github.repository_owner }}/stevedore:v0.0.1"}'
